name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Hotfixes'
    label: 'fix'
  - title: '🔧 Refactors'
    label: 'refactor'
  - title: '📃 Docs'
    label: 'docs'
  - title: '📦 Chore'
    label: 'chore'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  ## Describe changes
  $CHANGES
  ### Issue ticket number and link (optional)